config/routes.rb
Tecportal::Application.routes.draw do

  get  'plugin_bamboo_hr/index'
  get  'plugin_bamboo_hr/settings'
  get  'plugin_bamboo_hr/save_settings'
  get  'plugin_bamboo_hr/import_employees'
  get  'plugin_bamboo_hr/progress'

  get  'plugin_service_master/schedules'
  get  'plugin_service_master/events'
  get  'plugin_service_master/settings'
  post 'plugin_service_master/save_settings'
  get  'plugin_service_master/team_list'
  get  'plugin_service_master/customer_list'
  get  'plugin_service_master/employee_list'
  get  'plugin_service_master/get_team'
  post 'plugin_service_master/save_team'
  get  'plugin_service_master/create_team'
  get  'plugin_service_master/delete_team'
  get  'plugin_service_master/get_customer'
  get  'plugin_service_master/get_pattern'
  post 'plugin_service_master/save_pattern'
  get  'plugin_service_master/create_pattern'
  get  'plugin_service_master/delete_pattern'
  get  'plugin_service_master/get_employee'
  post 'plugin_service_master/save_employee'
  get  'plugin_service_master/assign_pattern'
  get  'plugin_service_master/delete_emp_pattern'
  get  'plugin_service_master/import_employees'
  get  'plugin_service_master/import_workgroups'
  post 'plugin_service_master/save_schedule'
  post 'plugin_service_master/delete_schedule'
  get  'plugin_service_master/team_filter'
  get  'plugin_service_master/cust_filter'
  get  'plugin_service_master/next_week'
  get  'plugin_service_master/prev_week'
  get  'plugin_service_master/next_event_week'
  get  'plugin_service_master/prev_event_week'
  get  'plugin_service_master/export_scheds'
  get  'plugin_service_master/generate_scheds'
  get  'plugin_service_master/progress'

  get  'plugin_snohomish/index'
  get  'plugin_snohomish/settings'
  post 'plugin_snohomish/save_settings'
  get  'plugin_snohomish/round_hours'

  get  'plugin_fmc/index'
  get  'plugin_fmc/settings'
  post 'plugin_fmc/save_settings'
  get  'plugin_fmc/create_export'
  get  'plugin_fmc/progress'
  get  'plugin_fmc/finish'
  get  'plugin_fmc/download_file'

  get  'plugin_visualizer/index'
  get  'plugin_visualizer/settings'
  post 'plugin_visualizer/save_settings'
  get  'plugin_visualizer/create_report'
  get  'plugin_visualizer/download_report'

  get  'plugin_aod_time_entry/index'
  get  'plugin_aod_time_entry/settings'
  get  'plugin_aod_time_entry/start'
  get  'plugin_aod_time_entry/end'

  get  'tec_plugins/list' 

  devise_for :users; 

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get  'home/dashboard' 
  root :to => 'home#index'

end

app/controllers/plugin_aod_time_entry_controller.rb
class PluginAodTimeEntryController < ApplicationController
  before_filter :authenticate_user!
  layout "plugin"
  
  account = ""
  username = ""
  password = ""

  # Get User Settings

  # Get Customer Settings

  # Create interface to AoD
  # @@aod = ApplicationHelper::AodInterface.new(account, username, password)

  def index
  end

  def settings
  end

  def start  	
  	# @@aod = PluginsHelper::AodInterface.new(account, username, password)
  	# response = @@aod.extract_ranged_transactions_using_hyper_query( message: { 
  	# 	hyperQueryName: "All Employees", 
  	# 	dateRangeEnum: "drToday", 
  	# 	minDate: "", 
  	# 	maxDate: "" 
  	# })	
  	# @transactions = response.body[:t_ae_emp_transaction]
  end

  def end
  end
end

app/helpers/plugin_aod_time_entry_helper.rb
module PluginAodTimeEntryHelper
end

app/views/plugin_aod_time_entry/end.html.erb
<div class="plugin-aod-time-entry">

  <!-- Header -->
  <h3>AoD Time Entry</h3> 
  <br>
  
  <!-- Content -->
  <div class="label">Quantity Run</div>
	<input type="number"><br>

	<div class="label">Scrapped</div>
	<input type="number"><br>

	<div class="label">Total</div>
	<input type="number"><br>

	<br>
	<%= link_to "Submit", plugin_aod_time_entry_index_path, class: "submit-button" %>

</div>

app/views/plugin_aod_time_entry/index.html.erb
<div class="plugin-aod-time-entry">

  <!-- Header -->
  <h3>AoD Time Entry</h3> 
  <br>
  
  <!-- Content -->
	<%= link_to "Start", plugin_aod_time_entry_start_path, class: "start-button" %>
	<div class="v-spacer"></div>
	<%= link_to "End", plugin_aod_time_entry_end_path, class: "end-button" %>

</div>

app/views/plugin_aod_time_entry/settings.html.erb
<div class="plugin-aod-time-entry">

  <h3>Settings</h3>
  <p>
    ...
  </p>

</div>

app/views/plugin_aod_time_entry/start.html.erb
<div class="plugin-aod-time-entry">

  <!-- Header -->
  <h3>AoD Time Entry</h3> 
  <br>
  
  <!-- Content -->
  <div class="label">Employee ID</div>
	<input type="number"><br>
	<div class="v-spacer"></div>

	<div class="label">Work Order</div>
	<select>
		<option value="1">Work Order #1</option>
		<option value="2">Work Order #2</option>
		<option value="3">Work Order #3</option>
		<option value="4">Work Order #4</option>
		<option value="5">Work Order #5</option>
		<option value="6">Work Order #6</option>
		<option value="7">Work Order #7</option>
		<option value="8">Work Order #8</option>
		<option value="9">Work Order #9</option>
	</select>
	<div class="v-spacer"></div>
	<div class="label">Sequence</div>
	<select>
		<option value="1">Sequence #1</option>
		<option value="2">Sequence #2</option>
		<option value="3">Sequence #3</option>
		<option value="4">Sequence #4</option>
		<option value="5">Sequence #5</option>
		<option value="6">Sequence #6</option>
		<option value="7">Sequence #7</option>
		<option value="8">Sequence #8</option>
		<option value="9">Sequence #9</option>
	</select>
	<div class="v-spacer"></div>
	<div class="v-spacer"></div>

	<%= link_to "Submit", plugin_aod_time_entry_index_path, class: "submit-button" %>

</div>