config/routes.rb
Tecportal::Application.routes.draw do

  get  'plugin_bamboo_hr/index'
  get  'plugin_bamboo_hr/settings'
  get  'plugin_bamboo_hr/save_settings'
  get  'plugin_bamboo_hr/import_employees'
  get  'plugin_bamboo_hr/progress'

  get  'plugin_service_master/schedules'
  get  'plugin_service_master/events'
  get  'plugin_service_master/settings'
  post 'plugin_service_master/save_settings'
  get  'plugin_service_master/team_list'
  get  'plugin_service_master/customer_list'
  get  'plugin_service_master/employee_list'
  get  'plugin_service_master/get_team'
  post 'plugin_service_master/save_team'
  get  'plugin_service_master/create_team'
  get  'plugin_service_master/delete_team'
  get  'plugin_service_master/get_customer'
  get  'plugin_service_master/get_pattern'
  post 'plugin_service_master/save_pattern'
  get  'plugin_service_master/create_pattern'
  get  'plugin_service_master/delete_pattern'
  get  'plugin_service_master/get_employee'
  post 'plugin_service_master/save_employee'
  get  'plugin_service_master/assign_pattern'
  get  'plugin_service_master/delete_emp_pattern'
  get  'plugin_service_master/import_employees'
  get  'plugin_service_master/import_workgroups'
  post 'plugin_service_master/save_schedule'
  post 'plugin_service_master/delete_schedule'
  get  'plugin_service_master/team_filter'
  get  'plugin_service_master/cust_filter'
  get  'plugin_service_master/next_week'
  get  'plugin_service_master/prev_week'
  get  'plugin_service_master/next_event_week'
  get  'plugin_service_master/prev_event_week'
  get  'plugin_service_master/export_scheds'
  get  'plugin_service_master/generate_scheds'
  get  'plugin_service_master/progress'

  get  'plugin_snohomish/index'
  get  'plugin_snohomish/settings'
  post 'plugin_snohomish/save_settings'
  get  'plugin_snohomish/round_hours'

  get  'plugin_fmc/index'
  get  'plugin_fmc/settings'
  post 'plugin_fmc/save_settings'
  get  'plugin_fmc/create_export'
  get  'plugin_fmc/progress'
  get  'plugin_fmc/finish'
  get  'plugin_fmc/download_file'

  get  'plugin_visualizer/index'
  get  'plugin_visualizer/settings'
  post 'plugin_visualizer/save_settings'
  get  'plugin_visualizer/create_report'
  get  'plugin_visualizer/download_report'

  get  'plugin_aod_time_entry/index'
  get  'plugin_aod_time_entry/settings'
  get  'plugin_aod_time_entry/start'
  get  'plugin_aod_time_entry/end'

  get  'tec_plugins/list' 

  devise_for :users; 

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get  'home/dashboard' 
  root :to => 'home#index'

end

app/views/shared/_pluginlist.html.erb
<% UserSettings.where(user_id: current_user.id).each do |u| %>
  <% if u.plugin_id == 0 %>
    <%= link_to "AoD Time Entry", plugin_aod_time_entry_index_path, 
        class: "js-plugin" %>
  <% elsif u.plugin_id == 1 %>
    <%= link_to "Protocall Visualizer", plugin_visualizer_index_path, 
        class: "js-plugin" %>
  <% elsif u.plugin_id == 2 %>
    <%= link_to "FMC Payroll Export", plugin_fmc_index_path, 
        class: "js-plugin" %>
  <%# elsif u.plugin_id == 3 %>
    <%#= link_to "Snohomish Timecard Editor", plugin_snohomish_index_path, 
        class: "js-plugin" %>
  <% elsif u.plugin_id == 4 %>
    <%= link_to "Service Master", plugin_service_master_schedules_path, 
        class: "js-plugin" %>
  <% elsif u.plugin_id == 5 %>
    <%= link_to "BambooHR", plugin_bamboo_hr_index_path, 
        class: "js-plugin" %>
  <% end %>
<% end %>

<!-- Scripts -->
<script>
  // Show the spinner when you click on a plugin
    $('.js-plugin').click(function() {
    $('#spinner').show();
  });
</script>

app/views/shared/_progressbar.html.erb
<div id="progress-bar-wrapper">
  <div id="progress-status"></div>
  <div id="progress-bar"><div id="progress-label"></div></div>
</div>

app/views/shared/_spinner.html.erb
<div id="spinner-container">
  <div id="spinner"></div>
</div>

<script>
  // Setup options for spin.js
  // Reference:  htttp://fgnass.github.io/spin.js/

  // Smaller spinner
  var options = {
    lines: 11, // The number of lines to draw
    length: 12, // The length of each line
    width: 4, // The line thickness
    radius: 11, // The radius of the inner circle
    corners: 1, // Corner roundness (0..1)
    rotate: 0, // The rotation offset
    direction: 1, // 1: clockwise, -1: counterclockwise
    color: '#000', // #rgb or #rrggbb or array of colors
    speed: 1.2, // Rounds per second
    trail: 54, // Afterglow percentage
    shadow: false, // Whether to render a shadow
    hwaccel: false, // Whether to use hardware acceleration
    className: 'spinner', // The CSS class to assign to the spinner
    zIndex: 100, // The z-index (defaults to 2000000000)
    top: 'auto', // Top position relative to parent in px
    left: 'auto' // Left position relative to parent in px
  };

  // // Big spinner
  // var options = {
  //   lines: 11, // The number of lines to draw
  //   length: 18, // The length of each line
  //   width: 5, // The line thickness
  //   radius: 19, // The radius of the inner circle
  //   corners: 1, // Corner roundness (0..1)
  //   rotate: 0, // The rotation offset
  //   direction: 1, // 1: clockwise, -1: counterclockwise
  //   color: '#000', // #rgb or #rrggbb or array of colors
  //   speed: 1.2, // Rounds per second
  //   trail: 54, // Afterglow percentage
  //   shadow: false, // Whether to render a shadow
  //   hwaccel: false, // Whether to use hardware acceleration
  //   className: 'spinner', // The CSS class to assign to the spinner
  //   zIndex: 2e9, // The z-index (defaults to 2000000000)
  //   top: 'auto', // Top position relative to parent in px
  //   left: 'auto' // Left position relative to parent in px
  // };

  //   // Thin spinner
  //     var options = {
  //   lines: 7, // The number of lines to draw
  //   length: 17, // The length of each line
  //   width: 2, // The line thickness
  //   radius: 14, // The radius of the inner circle
  //   corners: 1, // Corner roundness (0..1)
  //   rotate: 0, // The rotation offset
  //   direction: 1, // 1: clockwise, -1: counterclockwise
  //   color: '#000', // #rgb or #rrggbb or array of colors
  //   speed: 1.4, // Rounds per second
  //   trail: 53, // Afterglow percentage
  //   shadow: false, // Whether to render a shadow
  //   hwaccel: false, // Whether to use hardware acceleration
  //   className: 'spinner', // The CSS class to assign to the spinner
  //   zIndex: 2e9, // The z-index (defaults to 2000000000)
  //   top: 'auto', // Top position relative to parent in px
  //   left: 'auto' // Left position relative to parent in px
  // };

  // // Dots spinner
  // var options = {
  //   lines: 11, // The number of lines to draw
  //   length: 0, // The length of each line
  //   width: 6, // The line thickness
  //   radius: 27, // The radius of the inner circle
  //   corners: 1, // Corner roundness (0..1)
  //   rotate: 0, // The rotation offset
  //   direction: 1, // 1: clockwise, -1: counterclockwise
  //   color: '#000', // #rgb or #rrggbb or array of colors
  //   speed: 1.4, // Rounds per second
  //   trail: 53, // Afterglow percentage
  //   shadow: false, // Whether to render a shadow
  //   hwaccel: false, // Whether to use hardware acceleration
  //   className: 'spinner', // The CSS class to assign to the spinner
  //   zIndex: 2e9, // The z-index (defaults to 2000000000)
  //   top: 'auto', // Top position relative to parent in px
  //   left: 'auto' // Left position relative to parent in px
  // };

  var target = document.getElementById('spinner');
  var spinner = new Spinner(options).spin(target);

</script>