config/routes.rb
Tecportal::Application.routes.draw do

  get  'plugin_bamboo_hr/index'
  get  'plugin_bamboo_hr/settings'
  get  'plugin_bamboo_hr/save_settings'
  get  'plugin_bamboo_hr/import_employees'
  get  'plugin_bamboo_hr/progress'

  get  'plugin_service_master/schedules'
  get  'plugin_service_master/events'
  get  'plugin_service_master/settings'
  post 'plugin_service_master/save_settings'
  get  'plugin_service_master/team_list'
  get  'plugin_service_master/customer_list'
  get  'plugin_service_master/employee_list'
  get  'plugin_service_master/get_team'
  post 'plugin_service_master/save_team'
  get  'plugin_service_master/create_team'
  get  'plugin_service_master/delete_team'
  get  'plugin_service_master/get_customer'
  get  'plugin_service_master/get_pattern'
  post 'plugin_service_master/save_pattern'
  get  'plugin_service_master/create_pattern'
  get  'plugin_service_master/delete_pattern'
  get  'plugin_service_master/get_employee'
  post 'plugin_service_master/save_employee'
  get  'plugin_service_master/assign_pattern'
  get  'plugin_service_master/delete_emp_pattern'
  get  'plugin_service_master/import_employees'
  get  'plugin_service_master/import_workgroups'
  post 'plugin_service_master/save_schedule'
  post 'plugin_service_master/delete_schedule'
  get  'plugin_service_master/team_filter'
  get  'plugin_service_master/cust_filter'
  get  'plugin_service_master/next_week'
  get  'plugin_service_master/prev_week'
  get  'plugin_service_master/next_event_week'
  get  'plugin_service_master/prev_event_week'
  get  'plugin_service_master/export_scheds'
  get  'plugin_service_master/generate_scheds'
  get  'plugin_service_master/progress'

  get  'plugin_snohomish/index'
  get  'plugin_snohomish/settings'
  post 'plugin_snohomish/save_settings'
  get  'plugin_snohomish/round_hours'

  get  'plugin_fmc/index'
  get  'plugin_fmc/settings'
  post 'plugin_fmc/save_settings'
  get  'plugin_fmc/create_export'
  get  'plugin_fmc/progress'
  get  'plugin_fmc/finish'
  get  'plugin_fmc/download_file'

  get  'plugin_visualizer/index'
  get  'plugin_visualizer/settings'
  post 'plugin_visualizer/save_settings'
  get  'plugin_visualizer/create_report'
  get  'plugin_visualizer/download_report'

  get  'plugin_aod_time_entry/index'
  get  'plugin_aod_time_entry/settings'
  get  'plugin_aod_time_entry/start'
  get  'plugin_aod_time_entry/end'

  get  'tec_plugins/list' 

  devise_for :users; 

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get  'home/dashboard' 
  root :to => 'home#index'

end

app/models/plugin_service_master/import_workgroups.rb
module PluginServiceMaster

  class ImportWorkgroups
    include ApplicationHelper

    attr_accessor :user_id, :settings, :wglevel
    def initialize user_id,  settings,  wglevel
      @user_id = user_id
      @settings = settings
      @wglevel = wglevel
    end
    
    def perform
      log "\n\nasync method", __method__, 0
      begin

        # Connect to AoD
        progress 20, 'Connecting to AoD'
        aod = create_conn(@settings)
        
        # Get workgroups
        progress 40, 'Getting workgroups'
        response = aod.call(
          :get_workgroups, message: {
            wGLevel: @wglevel,
            wGSortingOption: 'wgsNum' })  
        wgs = response.body[:t_ae_workgroup]

        wgcount = 0
        wgs.each_with_index do |wg, i|

          progress 40 + (60 * i / wgs.count), "Importing #{ i } of #{ wgs.count }"

          # Insert or Update this workgroup
          my_wg = PsvmWorkgroup.where(
            wg_level: wg[:wg_level], 
            wg_num:   wg[:wg_num]).first_or_initialize
          my_wg.wg_level  = wg[:wg_level]  unless wg[:wg_level].is_a? Hash
          my_wg.wg_num    = wg[:wg_num]    unless wg[:wg_num].is_a? Hash
          my_wg.wg_code   = wg[:wg_code]   unless wg[:wg_num].is_a? Hash
          my_wg.wg_name   = wg[:wg_name]   unless wg[:wg_num].is_a? Hash
          my_wg.save
          wgcount += 1
        end

        # Log how many updated
        log 'Updated workgroups:', wgcount

      rescue Exception => exc
        log 'exception', exc.message
        log 'exception backtrace', exc.backtrace
      ensure
        progress 100, ''
      end      
    end

    def progress percent, status
      cache_save @user_id, 'svm_import_progress', percent.to_s
      cache_save @user_id, 'svm_import_status', status
    end

  end
end

app/models/plugin_service_master/settings.rb
module PluginServiceMaster

  class Settings
    include ActiveModel::Serializers::JSON
    include ActiveModel::Validations
    include ActiveModel::Conversion
    extend  ActiveModel::Naming

    attr_accessor :account, :username, :password, :teamfilter, :custfilter, :weekstart

    def initialize(args = {})
      args.keys.each { |name| instance_variable_set "@" + name.to_s, args[name] }
      @account    ||= ''
      @username   ||= ''
      @password   ||= ''
      @teamfilter ||= 1
      @custfilter ||= 1
      @weekstart  ||= Date.today.beginning_of_week
    end

    def persisted?
      false
    end

    # For JSON Serialization
    def attributes=(hash)
      hash.each do |key, value|
        instance_variable_set("@#{key}", value)
      end
    end
    def attributes
      instance_values
    end

  end
end

app/controllers/plugin_service_master_controller.rb
class PluginServiceMasterController < ApplicationController
  before_filter :authenticate_user!
  around_filter :catch_exceptions
  layout "plugin_service_master"

  @@plugin_id = 4

  def schedules
    log __method__

    # Get plugin settings for this user
    cls = PluginServiceMaster::Settings
    if session[:settings].class != cls
       session[:settings] =
         get_settings(cls,
          current_user.id,
          current_user.customer_id,
          @@plugin_id)
    end

    # Get the dates for the week we're viewing
    session[:startdate] = session[:settings].weekstart || Date.today.beginning_of_week
    session[:enddate] = session[:startdate] + 6.days

    # Create view model vars
    @team_filter            = session[:team_filter] || ""
    @cust_filter            = session[:cust_filter] || ""
    @startdate              = session[:settings].weekstart || Date.today.beginning_of_week
    @enddate                = @startdate + 6.days
    @export_all             = session[:export_all]
    @overwrite_scheds       = session[:overwrite_scheds]
    @apply_to_all_customers = session[:apply_to_all_customers]
    @apply_to_future        = session[:apply_to_future]

    log 'team_filter', @team_filter
    log 'cust_filter', @cust_filter

    if session[:future_date].class == Date
      @future_date = session[:future_date].strftime "%m/%d/%Y"
    else
      @future_date = @enddate.strftime "%m/%d/%Y"
    end

    # Get workgroups
    @customers  = PsvmWorkgroup.where('wg_level = 3').order('wg_name')
    @activities = PsvmWorkgroup.where('wg_level = 5').order('wg_num')
    @teams      = PsvmWorkgroup.where('wg_level = 8').order('wg_name')

    # Get all the scheds for these filters
    scheds = get_filtered_scheds(@startdate, @enddate, 
                                 @team_filter, @cust_filter)
    # Get all their emps
    emps = PsvmEmp.where(filekey: scheds.map { |s| s.filekey })

    # Get all the emps assigned to patterns for these filters
    emps2 = get_filtered_emps(@team_filter, @cust_filter)

    # Add all the scheds for those emps
    scheds2 = PsvmSched.where(filekey: emps2.map { |e| e.filekey },
                               sch_date: @startdate..@enddate)
    # Merge both
    emps   += emps2
    scheds += scheds2

    # Remove duplicates and sort
    emps   = emps.uniq.sort_by &:fullname
    scheds = scheds.uniq.sort_by &:filekey

    # Make a viewweek
    @vw = PluginServiceMaster::ViewModels::ViewWeekVM.new(
      @startdate, 
      @enddate)

    # For each employee
    emps.each do |emp|

      # Make an empweek
      ew = PluginServiceMaster::ViewModels::EmpWeekVM.new(emp)

      # Add it to the viewweek
      @vw.emp_weeks << ew

      # For each pattern this emp is assigned to
      emp.patterns.each do |p|

        # Find the custweek for this pattern
        cw = nil
        customer = PsvmWorkgroup.where(wg_level: 3, wg_num: p.wg3).first
        ew.cust_weeks.each do |custweek|

          # See if we already have this custweek
          if custweek.customer.wg_num == p.wg3
            cw = custweek
            break
          end
        end

        # If we don't add it to the empweek
        if cw.nil?
          cw = PluginServiceMaster::ViewModels::CustWeekVM.new(
            customer)
          ew.cust_weeks << cw
        end

        # Find the teamweek for this sched
        tw = nil
        team = PsvmWorkgroup.where(wg_level: 8, wg_num: p.wg8).first
        cw.team_weeks.each do |teamweek|

          # See if we already have this teamweek
          if teamweek.team.wg_num == p.wg8
            tw = teamweek
            break
          end
        end

        # If we don't add it to the custweek
        if tw.nil?
          tw = PluginServiceMaster::ViewModels::TeamWeekVM.new(
            emp, customer, team, @startdate)
          cw.team_weeks << tw
        end
      end

      # For each sched
      scheds.each do |s|

        # If this sched is for this employee
        if s.filekey == emp.filekey

          # Find the custweek for this sched
          cw = nil
          customer = PsvmWorkgroup.where(
            wg_level: 3, wg_num: s.sch_wg3).first

          ew.cust_weeks.each do |custweek|

            # See if we already have this custweek
            if custweek.customer.wg_num == s.sch_wg3
              cw = custweek
              break
            end
          end

          # If we don't add it to the empweek
          if cw.nil?
            cw = PluginServiceMaster::ViewModels::CustWeekVM.new(
              customer)
            ew.cust_weeks << cw
          end

          # Find the teamweek for this sched
          tw = nil
          team = PsvmWorkgroup.where(
            wg_level: 8, wg_num: s.sch_wg8).first
          cw.team_weeks.each do |teamweek|

            # See if we already have this teamweek
            if teamweek.team.wg_num == s.sch_wg8
              tw = teamweek
              break
            end
          end

          # If we don't add it to the custweek
          if tw.nil?
            tw = PluginServiceMaster::ViewModels::TeamWeekVM.new(
              emp, customer, team, @startdate)
            cw.team_weeks << tw
          end

          # Add this schedule to the teamweek
          tw.day1 = s if s.sch_date.monday?
          tw.day2 = s if s.sch_date.tuesday?
          tw.day3 = s if s.sch_date.wednesday?
          tw.day4 = s if s.sch_date.thursday?
          tw.day5 = s if s.sch_date.friday?
          tw.day6 = s if s.sch_date.saturday?

          # Tally hours
          tw.total_hours += s.sch_hours_hund
          cw.total_hours += s.sch_hours_hund
          ew.total_hours += s.sch_hours_hund
        end
      end

      # # Look up any events for this employee
      # events = PsvmSched.where(is_event: true,
      #                          sch_wg3: customer.wg_num,
      #                          sch_date: @startdate..@enddate)

      # log 'events', events
      
      # # For each event
      # events.each do |e|

      #   # Create a teamweek for it
      #   tw = PluginServiceMaster::ViewModels::TeamWeekVM.new(
      #     emp, customer, 
      #     PsvmWorkgroup.new({ wg_level: 8, wg_name: e.label }),
      #     @startdate)
      #   cw.team_weeks << tw

      #   # Add this event to the teamweek
      #   tw.day1 = e if e.sch_date.monday?
      #   tw.day2 = e if e.sch_date.tuesday?
      #   tw.day3 = e if e.sch_date.wednesday?
      #   tw.day4 = e if e.sch_date.thursday?
      #   tw.day5 = e if e.sch_date.friday?
      #   tw.day6 = e if e.sch_date.saturday?

      #   # Tally hours
      #   tw.total_hours += e.sch_hours_hund
      #   cw.total_hours += e.sch_hours_hund
      #   ew.total_hours += e.sch_hours_hund
      # end

      # Check for any overlapping schedules
      ew.cust_weeks.each do |cw1|
        cw1.team_weeks.each do |tw1|
          ew.cust_weeks.each do |cw2|
            cw2.team_weeks.each do |tw2|
              if tw1.day1.id != tw2.day1.id &&
                 tw1.day1.sch_start_time < tw2.day1.sch_end_time &&
                 tw2.day1.sch_start_time < tw1.day1.sch_end_time
                 tw1.day1.overlapping = true;
                 tw2.day1.overlapping = true;
              end 
              if tw1.day2.id != tw2.day2.id &&
                 tw1.day2.sch_start_time < tw2.day2.sch_end_time &&
                 tw2.day2.sch_start_time < tw1.day2.sch_end_time
                 tw1.day2.overlapping = true;
                 tw2.day2.overlapping = true;
              end 
              if tw1.day3.id != tw2.day3.id &&
                 tw1.day3.sch_start_time < tw2.day3.sch_end_time &&
                 tw2.day3.sch_start_time < tw1.day3.sch_end_time
                 tw1.day3.overlapping = true;
                 tw2.day3.overlapping = true;
              end 
              if tw1.day4.id != tw2.day4.id &&
                 tw1.day4.sch_start_time < tw2.day4.sch_end_time &&
                 tw2.day4.sch_start_time < tw1.day4.sch_end_time
                 tw1.day4.overlapping = true;
                 tw2.day4.overlapping = true;
              end 
              if tw1.day5.id != tw2.day5.id &&
                 tw1.day5.sch_start_time < tw2.day5.sch_end_time &&
                 tw2.day5.sch_start_time < tw1.day5.sch_end_time
                 tw1.day5.overlapping = true;
                 tw2.day5.overlapping = true;
              end 
              if tw1.day6.id != tw2.day6.id &&
                 tw1.day6.sch_start_time < tw2.day6.sch_end_time &&
                 tw2.day6.sch_start_time < tw1.day6.sch_end_time
                 tw1.day6.overlapping = true;
                 tw2.day6.overlapping = true;
              end 
            end
          end
        end
      end

      # If total hours > 29, print exception
      ew.exceptions = 'Over limit!' if ew.total_hours >= 29.0
    end
  end

  def events
    log __method__

    # Get the dates for the week we're viewing
    session[:startdate] = session[:settings].weekstart || Date.today.beginning_of_week
    session[:enddate] = session[:startdate] + 6.days

    # Create view model vars
    @team_filter            = session[:team_filter] || ""
    @cust_filter            = session[:cust_filter] || ""
    @startdate              = session[:settings].weekstart || Date.today.beginning_of_week
    @enddate                = @startdate + 6.days

    log 'cust_filter', @cust_filter
    
    # Get workgroups
    @customers  = PsvmWorkgroup.where('wg_level = 3').order('wg_name')

    # Get all the events for these filters
    events = get_filtered_events(@startdate, @enddate, @cust_filter)

    # Get all their customers
    customers = PsvmWorkgroup.where(
      wg_level: 3, 
      wg_num: events.map { |e| e.sch_wg3 })
    .sort_by &:wg_name

    # If there were none, create a dummy customer
    if customers.nil? || customers.empty?
      customers = []
      customers << PsvmWorkgroup.new({ wg_level: 3, wg_name: 'None' })
    end

    # Make a viewweek

app/helpers/plugin_service_master_helper.rb
module PluginServiceMasterHelper

  def generate_td_attr sched
    attributes = "class='sched"
    
    # If this <td> has a schedule
    if sched.present?

      # Change <td> class depending on activity
      if sched.sch_wg5.present?
        case sched.sch_wg5
          when 2 
            attributes += " projectwork"
          when 3 
            attributes += " housekeeping"
          when 4 
            attributes += " daycleaning"
          when 5 
            attributes += " supervision"
        end 
      end

      # Add extra class if this is an overlapping sched
      if sched.overlapping.present?
        attributes += " overlap"
      end

      # Add extra attributes to hold sched properties      
      attributes +=
        "' schid='#{ sched.id }' 
         filekey='#{ sched.filekey }' 
         date='#{ sched.sch_date }'
         starttime='#{ sched.sch_start_time.strftime('%-l:%M %P') }'
         endtime='#{ sched.sch_end_time.strftime('%-l:%M %P') }'
         cust='#{ sched.sch_wg3 }'
         team='#{ sched.sch_wg8 }'
         activity='#{ sched.sch_wg5 }'
         label='#{ sched.label }'
         title='#{ sched.sch_hours_hund.to_f.round(2) } hours'"
    else
      attributes +=
      "' schid filekey date starttime endtime cust team activity label"
    end

    attributes
  end

  def generate_td_content(sched, show_label = false)
    if sched.present? && sched.id.present?
      if show_label
        sched.label
      else
        if sched.sch_start_time.hour > 12
          "#{ sched.sch_start_time.strftime('%-l:%M %P') } -
           #{ sched.sch_end_time.strftime('%-l:%M %P') }"
        else
          "#{ sched.sch_start_time.strftime('%-l:%M') } -
           #{ sched.sch_end_time.strftime('%-l:%M') }"
        end
      end
    end
  end

end

app/views/plugin_service_master/_event_popup.html.erb
<div id="event-popup">
  <form id="form-popup">
    <div>
      <%= label_tag :sch_wg3, 'Customer' %>
      <%= select_tag :sch_wg3, options_for_select(@customers.map { |a| [ a.wg_name, a.wg_num ] }), prompt: "Select Customer" %>
    </div>
    <br>
    <div>
      <%= hidden_field_tag :schid %>
      <%= hidden_field_tag :filekey, 0 %>
      <%= hidden_field_tag :sch_date %>
      <%= hidden_field_tag :is_event, true %>
    </div>
    <div>
      <%= label_tag :label, 'Label' %>
      <%= text_field_tag :label %>
    </div>
    <div>
      <%= label_tag :sch_start_time, 'Start Time' %>
      <%= text_field_tag :sch_start_time %>
    </div>
    <div>
      <%= label_tag :sch_end_time, 'End Time' %>
      <%= text_field_tag :sch_end_time %>
    </div>
    <br>
    <input type="submit" id='save-sched-btn' value="OK">
    <input type="submit" id='close-sched-btn' value="Cancel">
    <!-- <input type="submit" id='copy-sched-btn' value="Copy"> -->
    <input type="submit" id='delete-sched-btn' value="Delete">
  </form>
</div>

app/views/plugin_service_master/_links.html.erb
<div id="links">
  <a id="expand-btn" href="">>></a>
  <div id="links-expand">
    <%= link_to "Schedules", plugin_service_master_schedules_path %>
    <%= link_to "Employees", plugin_service_master_employee_list_path %>
    <%= link_to "Teams",     plugin_service_master_team_list_path %>
    <%= link_to "Customers", plugin_service_master_customer_list_path %>
    <%= link_to "Events",    plugin_service_master_events_path %>
    <% if current_user.customer_admin? %>
      <%= link_to "AoD",     plugin_service_master_settings_path %>
    <% else %>
      <a href=""> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </a>
    <% end %>
  </div>
  <%= link_to "Home", home_dashboard_path, id: "home-btn" %>
</div>

<script>

  // Expand button shows links
  $('#expand-btn').click(function(e) {
    e.preventDefault();
    if ($('#links-expand').width() == 0)
    {
      expandMenu();
    }
    else
    {
      shrinkMenu();
    }
  });

  function expandMenu() {
    $('#expand-btn').html('>>');
    $('#expand-btn').css('margin-right','-2px');
    $('#home-btn').css('margin-left','-7px');
    $("#links-expand").animate({
      "width": "465px",
    }, 300 );
  }

  function shrinkMenu() {
    $('#expand-btn').html('<<');
    $('#expand-btn').css('margin-right','-5px');
    $('#home-btn').css('margin-left','0px');
    $("#links-expand").animate({
      "width": "0px",
    }, 300 );
  }

</script>

app/views/plugin_service_master/index.html.erb
<div class="plugin-service-master">
  <div id="index">

    <header>
      <%= link_to "<", plugin_service_master_prev_week_path %>
      <div class="daterange">
        <%= @startdate.strftime '%b %d' %> - 
        <%= @enddate  .strftime '%b %d' %>
      </div>
      <%= link_to ">", plugin_service_master_next_week_path %>
      <%= render partial: 'links' %>
      <div id="team-filter-wrap">
        <%= label_tag :team_filter, 'Team' %>
        <%= select_tag :team_filter, options_for_select(@teams.map { |a| [ a.wg_name, a.wg_num ] }, @team_filter), prompt: "Select Team" %>
      </div>
      <div id="cust-filter-wrap">
        <%= label_tag :cust_filter, 'Customer' %>
        <%= select_tag :cust_filter, options_for_select(@customers.map { |a| [ a.wg_name, a.wg_num ] }, @cust_filter), prompt: "Select Customer" %>
      </div>
    </header>

    <main>
      <table id="main-table" class="popup-owner-js">
        <thead>
          <tr>
            <th class="name">Name</th>
            <th class="cust">Customer</th>
            <th class="team">Team</th>
            <th class="sched">Monday</br><%= (@startdate + 0.days).strftime('%-m/%-d') %></th>
            <th class="sched">Tuesday</br><%= (@startdate + 1.days).strftime('%-m/%-d') %></th>
            <th class="sched">Wednesday</br><%= (@startdate + 2.days).strftime('%-m/%-d') %></th>
            <th class="sched">Thursday</br><%= (@startdate + 3.days).strftime('%-m/%-d') %></th>
            <th class="sched">Friday</br><%= (@startdate + 4.days).strftime('%-m/%-d') %></th>
            <th class="sched">Saturday</br><%= (@startdate + 5.days).strftime('%-m/%-d') %></th>
            <th class="custtotal">Cust.</br>Total</th>
            <th class="emptotal">Emp.</br>Total</th>
            <th class="outside"></th>
          </tr>
        </thead>
        <% @v.emp_weeks.each_with_index do |ew, index| %>
          <tr <%= raw 'class="even"' if index.even? %>>
            <td class="name" rowspan="<%= ew.cust_weeks.count + 1 %>">
              <div class="name-wrapper"><%= "#{ ew.employee.first_name } #{ ew.employee.last_name }" %></div>
              <span class="idnum"><%= "#{ ew.employee.emp_id }" %></span> &nbsp;
              <span class="team"><%= "#{ ew.employee.custom1 }" if ew.employee.custom1.present? %></span>
            </td>
            <td class="flattened" colspan="8"></td>
            <td class="emptotal" rowspan="<%= ew.cust_weeks.count + 1 %>">
              <%= ew.total_hours.round(2) %>
            </td>
            <td class="overlimit outside" rowspan="<%= ew.cust_weeks.count + 1 %>">
              <%= ew.exceptions %>
            </td>
          </tr>
          <% ew.cust_weeks.each do |cw| %>
            <tr <%= raw 'class="even"' if index.even? %>>
              <td class="cust"><%= "#{ cw.customer.wg_name }" %>&nbsp;</td>
              <td class="team"><%= "Team Name!!!" %>&nbsp;</td>
              <td <%= raw generate_td_attr(cw.day1) %>> <%= raw generate_td_content(cw.day1) %></td>
              <td <%= raw generate_td_attr(cw.day2) %>> <%= raw generate_td_content(cw.day2) %></td>
              <td <%= raw generate_td_attr(cw.day3) %>> <%= raw generate_td_content(cw.day3) %></td>
              <td <%= raw generate_td_attr(cw.day4) %>> <%= raw generate_td_content(cw.day4) %></td>
              <td <%= raw generate_td_attr(cw.day5) %>> <%= raw generate_td_content(cw.day5) %></td>
              <td <%= raw generate_td_attr(cw.day6) %>> <%= raw generate_td_content(cw.day6) %></td>
              <td class="custtotal"><%= cw.total_hours.round(2) %></td>
            </tr>
          <% end %>
        <% end %>
        <%= render partial: "sched_popup", locals: { editing_customer: true } %>
      </table>
      <%= render partial: "legend" %>
      
      <form id="export-scheds-form">
        <input id="export-btn" type="submit" value="Export to AoD"><br>

        <%= check_box_tag "export_all", true, @export_all %>
        <%= label_tag(:export_all, "Export All") %><br>
      </form>

      <form id="gen-scheds-form" action="generate_scheds" method="get">
        <input id="generate-btn" type="submit" value="Generate Schedules"><br>
        
        <%= check_box_tag "overwrite_scheds", true, @overwrite_scheds %>
        <%= label_tag(:overwrite_scheds, "Overwrite Schedules") %><br>
        
        <%= check_box_tag "apply_to_all_customers", true, @apply_to_all_customers %>
        <%= label_tag(:apply_to_all_customers, "Apply to All Customers") %><br>
        
        <%= check_box_tag "apply_to_future", true, @apply_to_future %>
        <%= label_tag(:apply_to_future, "Apply to Future Date: ") %>
        <%= text_field_tag(:future_date, @future_date, class: "date-picker") %>
      </form>

      <div id="export-all-confirm" title="Export All Schedules?">
        <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0; z-index: 900"></span>Exporting all schedules could take a while.  Proceed?</p>
      </div>

      <%= render "shared/spinner" %>
      <%= render "shared/progressbar" %>

    </main>
  </div>  
</div>  
      fix lines 26, 27

<%= render partial: "scripts" %>

<!-- Scripts -->
<script>

  // Init progress bar
  var progressbar = $( "#progress-bar" );
  var progressLabel = $( "#progress-label" );
  
  progressbar.progressbar({
    value: 0,
    change: function() {
      progressLabel.text( progressbar.progressbar( "value" ) + "%" );
    },
    complete: function() {
      progressLabel.text( "Complete!" );
    }
  });

  // Init date picker
  $('.date-picker').datepicker();

  // Set expand btn icon to << for this page only 
  $('#expand-btn').html("<<");

  function poll()
  {
    $.get('progress', { progress_type: "export_scheds" }, function(data) {

      // If job completed
      if (data === true)
      {
        // Show results
        $('#progress-status').text('Finished')
        $('#progress-bar').progressbar('value', 100);

        // Hide spinner
        $('#spinner').hide();
      }
      else if (data.status)
      {
        // Show status
        $('#progress-status').text(data.status)
        $('#progress-bar').progressbar('value', parseInt(data.progress)); 

        // If job processing
        if (data.status != '')
        {
          // Show spinner and check status again in 2 seconds
          $('#spinner').show();
          setTimeout(poll, 1000);
        }
      }
    });
  }

  // When the user clicks the generate button
  $( "#generate-btn" ).click(function( event ) {

    // Show the spinner
    $('#spinner').show();
  });

  // When the user clicks the export button
  $( "#export-btn" ).click(function( event ) {
   
    // Stop form from submitting normally
    event.preventDefault();

    // Show the spinner and progress bar
    $('#spinner').show();

    // Get form inputs
    var exportAll = $('#export_all').prop('checked')

    // If Export All is checked
    if (exportAll === true) {

      // Confirm they want to proceed
      $("#export-all-confirm").dialog("open");

    } else {

      // Export just the scheds being viewed
      export_scheds(false);
    }
  });

  // Confirmation dialog for Export All
  $("#export-all-confirm").dialog({
    autoOpen: false,
    resizable: false,
    width:460,
    modal: true,
    buttons: {
      Yes: function() {
        $(this).dialog("close");

        // Export all schedules
        export_scheds(true);
      },
      No: function() {
        $(this).dialog("close");

        // Reset results
        $('#progress-status').text('')
        $('#progress-bar').progressbar('value', null);

        // Hide spinner
        $('#spinner').hide();
      }
    }
  });

  function export_scheds(exportAll) {

    // Send inputs and run the export
    $.get('export_scheds', { export_all: exportAll } );

    // Poll for status
    setTimeout(poll, 1000);
  }

</script>