config/routes.rb
Tecportal::Application.routes.draw do

  get  'plugin_bamboo_hr/index'
  get  'plugin_bamboo_hr/settings'
  get  'plugin_bamboo_hr/save_settings'
  get  'plugin_bamboo_hr/import_employees'
  get  'plugin_bamboo_hr/progress'

  get  'plugin_service_master/schedules'
  get  'plugin_service_master/events'
  get  'plugin_service_master/settings'
  post 'plugin_service_master/save_settings'
  get  'plugin_service_master/team_list'
  get  'plugin_service_master/customer_list'
  get  'plugin_service_master/employee_list'
  get  'plugin_service_master/get_team'
  post 'plugin_service_master/save_team'
  get  'plugin_service_master/create_team'
  get  'plugin_service_master/delete_team'
  get  'plugin_service_master/get_customer'
  get  'plugin_service_master/get_pattern'
  post 'plugin_service_master/save_pattern'
  get  'plugin_service_master/create_pattern'
  get  'plugin_service_master/delete_pattern'
  get  'plugin_service_master/get_employee'
  post 'plugin_service_master/save_employee'
  get  'plugin_service_master/assign_pattern'
  get  'plugin_service_master/delete_emp_pattern'
  get  'plugin_service_master/import_employees'
  get  'plugin_service_master/import_workgroups'
  post 'plugin_service_master/save_schedule'
  post 'plugin_service_master/delete_schedule'
  get  'plugin_service_master/team_filter'
  get  'plugin_service_master/cust_filter'
  get  'plugin_service_master/next_week'
  get  'plugin_service_master/prev_week'
  get  'plugin_service_master/next_event_week'
  get  'plugin_service_master/prev_event_week'
  get  'plugin_service_master/export_scheds'
  get  'plugin_service_master/generate_scheds'
  get  'plugin_service_master/progress'

  get  'plugin_snohomish/index'
  get  'plugin_snohomish/settings'
  post 'plugin_snohomish/save_settings'
  get  'plugin_snohomish/round_hours'

  get  'plugin_fmc/index'
  get  'plugin_fmc/settings'
  post 'plugin_fmc/save_settings'
  get  'plugin_fmc/create_export'
  get  'plugin_fmc/progress'
  get  'plugin_fmc/finish'
  get  'plugin_fmc/download_file'

  get  'plugin_visualizer/index'
  get  'plugin_visualizer/settings'
  post 'plugin_visualizer/save_settings'
  get  'plugin_visualizer/create_report'
  get  'plugin_visualizer/download_report'

  get  'plugin_aod_time_entry/index'
  get  'plugin_aod_time_entry/settings'
  get  'plugin_aod_time_entry/start'
  get  'plugin_aod_time_entry/end'

  get  'tec_plugins/list' 

  devise_for :users; 

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get  'home/dashboard' 
  root :to => 'home#index'

end

app/models/plugin_visualizer/sched_record.rb
module PluginVisualizer

  class SchedRecord
    attr_accessor \
      :lastname, 
      :firstname, 
      :employeeid, 
      :intime, 
      :outtime,
      :hours, 
      :earningscode, 
      :lunchplan, 
      :prepaiddate, 
      :workedflag, 
      :scheduletype, 
      :timezone

    def to_s
      @lastname.to_s.gsub(",", "") + "," +
      @firstname.to_s.gsub(",", "") + "," +
      @employeeid.to_s.gsub(",", "") + "," +
      @intime.strftime("%-m/%-d/%Y %H:%M") + "," +
      @outtime.strftime("%-m/%-d/%Y %H:%M") + "," +
      @hours.to_f.round(2).to_s + "," +
      @earningscode.to_s.gsub(",", "") + "," +
      @lunchplan.to_s.gsub(",", "") + "," +
      @prepaiddate.to_s + "," +
      @workedflag.to_s + "," +
      @scheduletype.to_s + "," +
      @timezone.to_s.gsub(",", "")
    end
  end
end

app/models/plugin_visualizer/settings.rb
module PluginVisualizer

  class Settings
    include ActiveModel::Serializers::JSON
    include ActiveModel::Validations
    include ActiveModel::Conversion
    extend ActiveModel::Naming

    attr_accessor :account, :username, :password

    def initialize(a = {})
      @account = a[:account]
      @username = a[:username]
      @password = a[:password]
    end

    def persisted?
      false
    end

    # For JSON Serialization
    def attributes=(hash)
      hash.each do |key, value|
        instance_variable_set("@#{key}", value)
      end
    end
    def attributes
      instance_values
    end

  end
end

app/models/plugin_visualizer/settings_vm.rb
module PluginVisualizer

  class SettingsVM
    include ActiveModel::Validations
    include ActiveModel::Conversion
    extend ActiveModel::Naming

    attr_accessor :owner, :account, :username, :password

    def initialize(a = {})
      @owner = a[:owner]
      @account = a[:account]
      @username = a[:username]
      @password = a[:password]
    end

    def persisted?
      false
    end
  end
end

app/controllers/plugin_visualizer_controller.rb
class PluginVisualizerController < ApplicationController
  before_filter :authenticate_user!
  layout "plugin"  

  @@plugin_id = 1

  def index
    log "\n\nmethod", 'index', 0
    begin
      # Get plugin settings for this user
      get_settings(PluginFMC::Settings, 
        current_user.id, 
        current_user.customer_id, 
        @@plugin_id)
      session[:settings] = settings

      # Connect to AoD
      aod = create_conn(settings)

      # Get pay periods from AoD
      response = aod.call(:get_pay_period_class_data,
        message: { payPeriodClassNum: 1 })  
      @payperiods = response.body[:t_ae_pay_period_info]
      @prevstart = @payperiods[:prev_start].to_datetime.strftime('%-m-%d-%Y')
      @prevend   = @payperiods[:prev_end]  .to_datetime.strftime('%-m-%d-%Y')
      @currstart = @payperiods[:curr_start].to_datetime.strftime('%-m-%d-%Y')
      @currend   = @payperiods[:curr_end]  .to_datetime.strftime('%-m-%d-%Y')

    rescue Exception => exc
      log 'exception', exc.message
      flash.now[:alert] = 'Unable to connect to AoD. Please check settings.'
    end
  end

  def settings
    log "\n\nmethod", 'settings', 0
    begin
      # If we just saved settings for someone
      if params[:settings_owner] && params[:settings_owner] != ''
        # Get their settings again
        settings = get_user_settings(PluginFMC::Settings,
          params[:settings_owner],
          @@plugin_id)
      else
        # Get the current user's settings
        params[:settings_owner] = current_user.id
        settings = get_user_settings(PluginFMC::Settings,
          params[:settings_owner],
          @@plugin_id)
      end

      # If we failed to get user settings
      if settings.nil?
        # Get customer settings
        params[:settings_owner] = ''
        settings = get_customer_settings(PluginFMC::Settings,
          current_user.customer_id,
          @@plugin_id)
      end

      # And if we still failed, create new settings for this customer
      settings ||= PluginVisualizer::Settings.new

      # Make a view model
      @settingsvm = PluginVisualizer::SettingsVM.new({
        owner: params[:settings_owner], 
        account: settings.account,
        username: settings.username,
        password: settings.password })

    rescue Exception => exc
      log 'exception', exc.message
      flash.now[:alert] = exc.message
    end
  end

  def save_settings
    log "\n\nmethod", 'save_settings', 0
    begin
      # Get settings for this plugin
      settingsvm = PluginVisualizer::SettingsVM.new(
        params[:plugin_visualizer_settings_vm])
      settings = PluginVisualizer::Settings.new(
        params[:plugin_visualizer_settings_vm])

      # Save these settings for the customer
      if settingsvm.owner.blank?
        s = CustomerSettings.where(
          customer_id: current_user.customer_id, 
          plugin_id: @@plugin_id).first_or_initialize
        s.data = settings.to_json
        s.save!
      else
        # Save these settings for the user
        s = UserSettings.where(
          user_id: settingsvm.owner.to_i, 
          plugin_id: @@plugin_id).first_or_initialize
        s.data = settings.to_json
        s.save!
      end

      params[:settings_owner] = settingsvm.owner
      flash.now[:message] = "Settings saved."

    rescue Exception => exc
      log 'exception', exc.message
      flash.now[:alert] = exc.message
    end
    redirect_to action: 'settings'
  end

  def create_report
    log "\n\nmethod", 'create_report', 0
    begin
      # Connect to AoD
      aod = create_conn(session[:settings])
      
      # Get pay period chosen
      if params[:payperiod] == "0"
        date_range = "drPrevPeriod" 
      else
        date_range = "drCurrPeriod" 
      end

      # # Get hyperqueries from AoD
      # response = aod.get_hyper_queries_simple()
      # @hyper_qs = response.body[:get_hyper_queries_simple_response] \
      #   [:return][:item]

      # Get schedules from AoD
      response = aod.call(:extract_ranged_schedules_using_hyper_query, 
        message: { 
          hyperQueryName: "All Employees",
          dateRangeEnum: date_range, 
          minDate: "",
          maxDate: "" })  
      schedules = response.body[:t_ae_schedule]

      # Make an array of sched records
      @schedrecords = Array.new

      # Convert the schedules to sched records
      schedules.each do |schedule|
        s = PluginVisualizer::SchedRecord.new
        s.lastname = schedule[:last_name]
        s.firstname = schedule[:first_name]
        s.employeeid = "J5X" + schedule[:emp_id].to_s.rjust(6, '0')
        s.intime = (schedule[:sch_date].to_s + " " + 
          schedule[:sch_start_time].to_s).to_datetime
        s.outtime = (schedule[:sch_date].to_s + " " + 
          schedule[:sch_end_time].to_s).to_datetime
        s.hours = schedule[:sch_hours_hund]
        s.earningscode = ""
        s.lunchplan = ""
        s.prepaiddate = ""
        s.workedflag = "TRUE"
        s.scheduletype = "Recurring"
        s.timezone = "PST"  

        # Offset 1 day for 3rd shifters whose end time would be 
        # numerically less than their start time
        if s.outtime <= s.intime
          s.outtime = s.outtime + 1
        end

        # If this is a benefit or planned absence schedule
        if schedule[:sch_type] == "steAbsPlnBen" || 
           schedule[:sch_type] == "steAbsPlnPayDes"
         
          aodnum = schedule[:benefit_id]
          ispaydes = false

          if schedule[:sch_type] == "steAbsPlnPayDes"
            aodnum = schedule[:pay_des_id]
            ispaydes = true
          end

          # Set the worked flag and lookup the earnings code for it
          s.workedflag = "FALSE"
          #s.earningscode = Helper.LookupBenefitMapping(isPayDes, aodNum);
        end

        # If a sched pattern did NOT generate this schedule
        if schedule[:sch_patt_id] == 0
          # Set the sched type
          s.scheduletype = "Deviation"
        end

        # Add this sched record to our array
        @schedrecords << s
      end

      # Create header for sched records
      @schedheader = 'Last Name,First Name,Employee ID,In time,Out time,Hours,Earnings Code,Scheduled Department,Lunch Plan,Pre-Paid Date,Worked Flag,Schedule Type,TimeZone,Department'

      # Create file, from header and sched records
      session[:schedfile] = 
        @schedheader + "\n" + @schedrecords.join("\n")

    rescue Exception => exc
      log 'exception', exc.message
      flash.now[:alert] = exc.message
    end
  end

  def download_report
    begin
      log "\n\nmethod", 'download_report', 0
      send_data session[:schedfile].to_s, 
        :filename => "schedules.csv", 
        :type => "text/plain" 
        
    rescue Exception => exc
      log 'exception', exc.message
      flash.now[:alert] = exc.message
    end
  end

end

app/helpers/plugin_visualizer_helper.rb
module PluginVisualizerHelper
end

app/views/plugin_visualizer/create_report.html.erb
<div class="plugin-visualizer">

  <!-- Header -->
  <h3>Visualizer Interface to AoD</h3> 
  <% if current_user.customer_admin? %>
    <%= link_to "Settings", plugin_visualizer_settings_path, class: "settings-btn" %>
  <% end %>
  
  <!-- Content -->
  <br>
  <%= link_to "Save to File", { action: "download_report" }, class: "button" %>
  <br>
  <textarea class="output"><%= h(session[:schedfile].to_s) %>
  </textarea>

</div>

app/views/plugin_visualizer/index.html.erb
<div class="plugin-visualizer">

  <!-- Header -->
  <h3>Visualizer Interface to AoD</h3> 
  <% if current_user.customer_admin? %>
    <%= link_to "Settings", plugin_visualizer_settings_path, class: "settings-btn" %>
  <% end %>
  
  <!-- Content -->
  <%= render "shared/spinner" %>
  <%= form_tag("create_report", method: "get") do %>

    <div class="entry">
      <%= label_tag(:payperiod, "Pay Period:") %>
      <select id="payperiod" name="payperiod">
        <option selected value="0">Previous</option>
        <option          value="1">Current</option>
      </select>
    </div>
    
    <div class="entry">
      <div class="label">Period Start: </div>
      <div class="label" id="period-start"></div>
    </div>
    
    <div class="entry">
      <div class="label">Period End: </div>
      <div class="label" id="period-end"></div>
    </div>

    <br>
    <input id="createreport" type="submit" value="Create Report">
  <% end %>
</div>  

<!-- Scripts -->
<script>
  // Show the spinner when you click 'Create Report'
  $('#createreport').click(function() {
    $('#spinner').show();
  });

  // Default to showing previous period dates
  $('#period-start').html('<%= @prevstart %>');
  $('#period-end').html('<%= @prevend %>');

  // Change the period dates when the user selects a period
  $('#payperiod').change(function() {
    if ($(this).val() === "0")
    {
      $('#period-start').html('<%= @prevstart %>');
      $('#period-end').html('<%= @prevend %>');
    }
    else
    {
      $('#period-start').html('<%= @currstart %>');
      $('#period-end').html('<%= @currend %>'); 
    }
  });
</script>

app/views/plugin_visualizer/settings.html.erb
<div class="plugin-visualizer">

  <!-- Header -->
  <h3>Settings</h3> 

  <!-- Content -->
  <%= render "shared/spinner" %>
  <%= form_for @settingsvm, url: {action: "save_settings", method: "post"} do |f| %>

    <div class="entry">
      <%= label_tag(:owner, "Applies to") %>
      <%= f.collection_select(:owner, current_user.customer.users, :id, :name, 
          include_blank: 'Default for all users') %>
    </div>

    <div class="entry">
      <%= label_tag :account %>
      <%= f.text_field :account %>
    </div>

    <div class="entry">
      <%= label_tag :username %>
      <%= f.text_field :username %>
    </div>

    <div class="entry">
      <%= label_tag :password %>
      <%= f.password_field :password, value: @settingsvm.password %>
    </div>

    <input type="submit" value="Save Settings">
  <% end %>
</div>